_bugtrait_type_: BugTraits

brain_size: 0.5
target_color: [0.5, 0.5, 0.5]
photosynthesis: 0.5
visual_range: 10.0
visual_sensitivity: 1.0
audio_sensitivity: 1.0
smell_sensitivity: 1.0
internal_sensitivity: 1.0

max_climb: 1.0
climb_efficiency: 0.5
move_effciency: 0.5

max_water: 10.0
water_gulp: 1.0
max_energy: 10.0
energy_gulp: 1.0
max_biomass: 10.0
biomass_gulp: 1.0

insulation: 0.5
armor: 0.1
senescence: 0.01
healing_rate: 0.1

newborn_energy: 1.0
newborn_biomass: 1.0
newborn_water: 1.0
newborn_color: [0.0, 1.0, 0.0]

movement_primitives: 1
attack_primitives: 1