defaults:
  - config
  - override hydra/sweeper: basic

hydra:
  sweeper:
    params:
      params.move_energy_cost: 0.005,0.01,0.02
      params.birth_energy_cost: 0.005,0.01,0.02
      traits.photosynthesis: 0.0,0.5,1.0
      traits.brain_size: 0.1,0.5,1.0